"""empty message

Revision ID: 1544b654fa60
Revises: 6a4d5eb25475
Create Date: 2021-06-24 23:48:01.328550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1544b654fa60'
down_revision = '6a4d5eb25475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=360), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shouts')
    # ### end Alembic commands ###
