"""fixtures

Revision ID: 1fe1bfa4b0bb
Revises: 1544b654fa60
Create Date: 2021-06-28 23:07:55.134753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe1bfa4b0bb'
down_revision = '1544b654fa60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('home', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away', sa.String(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('away'),
    sa.UniqueConstraint('home')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixtures')
    # ### end Alembic commands ###
